### ISSUE TITLE
using flash app

### ISSUE THREAD

**Issue by hughkojack** [crycode-de/mcp-can-boot-flash-app#3]
Hi peter,

I have can-usb device (MCP2515) connected to Linux server and I have installed the bootloader on Atmega32U4 in the can network with ID=42.

I am executing this command "npx mcp-can-boot-flash-app -r -f - -p m328p -m 0x0042" on the server and nothing will happen.

I assume by sending that command the MC should restart to execute the bootloader.

can you please help me, what else should I do?

**Comment by crycode-de** [comment]
Hi,

using this command, the flash-app will simply wait for the "Bootloader start" message from the MCU.
You have to trigger the MCU restart manually.

Optionally you may add `--reset 020040FF#4201FA` for example to the command to let the flash-app send the given CAN message to trigger the reset. In this example `020040FF` is the CAN-ID and `4201FA` the message data to send.
Of course your main application on the MCU have to handle this message and trigger the restart via watchdog reset for example. See [here](https://github.com/crycode-de/mcp-can-boot#how-to-reset-the-mcu-by-your-main-application) for an example how to do this.

**Comment by hughkojack** [comment]
Hi Peter,

Now I can reset the MC by reset command (--reset 790#F0)
but bootloader is not responding to flash-app which I think is related to can configuration in bootloader.

before I go further, I just want to know why do I need the reset cause (MCUSR/MCUCSR) in my main application?
My final goal is to upload a new sketch into MC via can-bus, so I cannot understand why the main application should know that it was reset by can-bus command.

**Comment by crycode-de** [comment]
After reset of the MCU the bootloader always sends the bootloader start message.
You should be able to see this in a camdump too with data like `xx xx 10 00 00 00 00 00` where xx xx contains the MCU ID you defined in the bootloader config.

If you don't need to know what triggert the MCU reset (like reset pin, watchdog, brown out, ...) in your main application you can simply ignore the MCUSR register.
